version: "3.7"
services:
  rhsso:
    image: viniciusmartinez/quarkus-rhsso:1.0
    ports:
      - "10080:8080"
    restart: always
  jaegger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
    restart: always
  conta:
    image: quarkus
    restart: always
    volumes: 
      - $HOME/.m2:/root/.m2
    build: 
      context: ./contacorrente
      dockerfile: ./src/main/docker/Dockerfile.native-micro
    container_name: conta_container
    # volumes:
    #   - ./contacorrente/src/main/docker:/work/
    ports:
      - "8080:8080"
